# https://docs.readthedocs.io/en/stable/config-file/v2.html#supported-settings

version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "3"
    rust: latest

python:
  install:
    - method: pip
      path: .

mkdocs:
  configuration: ./bindings/python/mkdocs.yml
