# https://docs.readthedocs.io/en/stable/config-file/v2.html#supported-settings

version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "3"
    rust: latest
  jobs:
    pre_create_environment:
      - "cd ./bindings/python && cargo build"

python:
  install:
    - method: pip
      path: ./bindings/python
      extra_requirements:
        - doc

mkdocs:
  configuration: ./bindings/python/mkdocs.yml
